import type { Metadata } from "next";
import "./globals.css";
import Client from "@components/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className="dark:bg-neutral-950 dark:text-white"
      >
        <Client>
        {children}
        </Client>
      </body>
    </html>
  );
}
